<?php
$actions = '';
require __DIR__ . '/../../components/page-header.php';
?>
<?php $referenceDoctor = $referenceDoctor ?? []; $isEdit = !empty($referenceDoctor['id']); ?>
<form method="post" action="<?= $isEdit ? app_url('reference-doctors/' . $referenceDoctor['id']) : app_url('reference-doctors') ?>" class="ajax-form">
<?= csrf_field() ?>
<div class="card content-card"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Name</label><input class="form-control" type="text" name="name" value="<?= e(old('name', $referenceDoctor['name'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Clinic Hospital</label><input class="form-control" type="text" name="clinic_hospital" value="<?= e(old('clinic_hospital', $referenceDoctor['clinic_hospital'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Mobile</label><input class="form-control" type="text" name="mobile" value="<?= e(old('mobile', $referenceDoctor['mobile'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?= e(old('email', $referenceDoctor['email'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Specialization</label><input class="form-control" type="text" name="specialization" value="<?= e(old('specialization', $referenceDoctor['specialization'] ?? '')) ?>"></div><div class="col-md-12"><label class="form-label">Address</label><textarea class="form-control" name="address" rows="3"><?= e(old('address', $referenceDoctor['address'] ?? '')) ?></textarea></div><div class="col-md-12"><label class="form-label">Remarks</label><textarea class="form-control" name="remarks" rows="3"><?= e(old('remarks', $referenceDoctor['remarks'] ?? '')) ?></textarea></div>
<div class="col-md-4"><div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="is_active" value="1" <?= (int) old('is_active', $referenceDoctor['is_active'] ?? 1) === 1 ? 'checked' : '' ?>><label class="form-check-label">Active</label></div></div>
</div><button class="btn btn-primary mt-4">Save</button><a class="btn btn-light mt-4" href="<?= app_url('reference-doctors') ?>">Cancel</a></div></div></form>
