<?php
$actions = '';
require __DIR__ . '/../../components/page-header.php';
?>
<?php $medicine = $medicine ?? []; $isEdit = !empty($medicine['id']); ?>
<form method="post" action="<?= $isEdit ? app_url('medicines/' . $medicine['id']) : app_url('medicines') ?>" class="ajax-form">
<?= csrf_field() ?>
<div class="card content-card"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Name</label><input class="form-control" type="text" name="name" value="<?= e(old('name', $medicine['name'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Generic Name</label><input class="form-control" type="text" name="generic_name" value="<?= e(old('generic_name', $medicine['generic_name'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Medicine Type</label><input class="form-control" type="text" name="medicine_type" value="<?= e(old('medicine_type', $medicine['medicine_type'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Default Dosage</label><input class="form-control" type="text" name="default_dosage" value="<?= e(old('default_dosage', $medicine['default_dosage'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Default Frequency</label><input class="form-control" type="text" name="default_frequency" value="<?= e(old('default_frequency', $medicine['default_frequency'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Default Duration</label><input class="form-control" type="text" name="default_duration" value="<?= e(old('default_duration', $medicine['default_duration'] ?? '')) ?>"></div><div class="col-md-12"><label class="form-label">Default Instructions</label><textarea class="form-control" name="default_instructions" rows="3"><?= e(old('default_instructions', $medicine['default_instructions'] ?? '')) ?></textarea></div>
<div class="col-md-4"><div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="is_active" value="1" <?= (int) old('is_active', $medicine['is_active'] ?? 1) === 1 ? 'checked' : '' ?>><label class="form-check-label">Active</label></div></div>
</div><button class="btn btn-primary mt-4">Save</button><a class="btn btn-light mt-4" href="<?= app_url('medicines') ?>">Cancel</a></div></div></form>
