-- Patient Clinical Chart (run once on local + live)
CREATE TABLE IF NOT EXISTS patient_clinical_charts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  patient_id INT UNSIGNED NOT NULL,
  chief_complaint TEXT NULL,
  drug_list TEXT NULL,
  habit TEXT NULL,
  test_advised TEXT NULL,
  tooth_notes JSON NULL,
  allotted_doctor_id INT UNSIGNED NULL,
  test_done TEXT NULL,
  next_appt_date DATE NULL,
  next_appt_time TIME NULL,
  next_appt_test TEXT NULL,
  next_appt_doctor_id INT UNSIGNED NULL,
  next_appointment_id INT UNSIGNED NULL,
  implant_appointment_id INT UNSIGNED NULL,
  lab_work LONGTEXT NULL,
  implant_work LONGTEXT NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  UNIQUE KEY uq_pcc_patient (patient_id),
  CONSTRAINT fk_pcc_patient FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
  CONSTRAINT fk_pcc_allotted_doctor FOREIGN KEY (allotted_doctor_id) REFERENCES doctors(id) ON DELETE SET NULL,
  CONSTRAINT fk_pcc_next_doctor FOREIGN KEY (next_appt_doctor_id) REFERENCES doctors(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
