<?php
$actions = '';
require __DIR__ . '/../../components/page-header.php';
?>
<?php $item = $item ?? []; $isEdit = !empty($item['id']); ?>
<form method="post" action="<?= $isEdit ? app_url('inventory/' . $item['id']) : app_url('inventory') ?>" class="ajax-form">
<?= csrf_field() ?>
<div class="card content-card"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Name</label><input class="form-control" type="text" name="name" value="<?= e(old('name', $item['name'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Category Id</label><input class="form-control" type="text" name="category_id" value="<?= e(old('category_id', $item['category_id'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Brand</label><input class="form-control" type="text" name="brand" value="<?= e(old('brand', $item['brand'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Unit</label><input class="form-control" type="text" name="unit" value="<?= e(old('unit', $item['unit'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Current Stock</label><input class="form-control" type="number" step="0.01" name="current_stock" value="<?= e(old('current_stock', $item['current_stock'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Minimum Stock</label><input class="form-control" type="number" step="0.01" name="minimum_stock" value="<?= e(old('minimum_stock', $item['minimum_stock'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Purchase Rate</label><input class="form-control" type="number" step="0.01" name="purchase_rate" value="<?= e(old('purchase_rate', $item['purchase_rate'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Batch No</label><input class="form-control" type="text" name="batch_no" value="<?= e(old('batch_no', $item['batch_no'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Expiry Date</label><input class="form-control" type="date" name="expiry_date" value="<?= e(old('expiry_date', $item['expiry_date'] ?? '')) ?>"></div>
<div class="col-md-4"><div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="is_active" value="1" <?= (int) old('is_active', $item['is_active'] ?? 1) === 1 ? 'checked' : '' ?>><label class="form-check-label">Active</label></div></div>
</div><button class="btn btn-primary mt-4">Save</button><a class="btn btn-light mt-4" href="<?= app_url('inventory') ?>">Cancel</a></div></div></form>
