<?php
$actions = '';
require __DIR__ . '/../../components/page-header.php';
?>
<?php $doctor = $doctor ?? []; $isEdit = !empty($doctor['id']); ?>
<form method="post" action="<?= $isEdit ? app_url('doctors/' . $doctor['id']) : app_url('doctors') ?>" class="ajax-form">
<?= csrf_field() ?>
<div class="card content-card"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">Name</label><input class="form-control" type="text" name="name" value="<?= e(old('name', $doctor['name'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Mobile</label><input class="form-control" type="text" name="mobile" value="<?= e(old('mobile', $doctor['mobile'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?= e(old('email', $doctor['email'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Qualification</label><input class="form-control" type="text" name="qualification" value="<?= e(old('qualification', $doctor['qualification'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Specialization</label><input class="form-control" type="text" name="specialization" value="<?= e(old('specialization', $doctor['specialization'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Registration Number</label><input class="form-control" type="text" name="registration_number" value="<?= e(old('registration_number', $doctor['registration_number'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Consultation Fee</label><input class="form-control" type="number" step="0.01" name="consultation_fee" value="<?= e(old('consultation_fee', $doctor['consultation_fee'] ?? '')) ?>"></div><div class="col-md-4"><label class="form-label">Slot Duration</label><input class="form-control" type="number" step="0.01" name="slot_duration" value="<?= e(old('slot_duration', $doctor['slot_duration'] ?? '')) ?>"></div>
<div class="col-md-4"><label class="form-label">Calendar Color</label><input class="form-control form-control-color w-100" type="color" name="calendar_color" value="<?= e(old('calendar_color', $doctor['calendar_color'] ?? '#00AEEF')) ?>" title="Doctor color on calendar"></div>
<div class="col-md-4"><div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="is_active" value="1" <?= (int) old('is_active', $doctor['is_active'] ?? 1) === 1 ? 'checked' : '' ?>><label class="form-check-label">Active</label></div></div>
</div><button class="btn btn-primary mt-4">Save</button><a class="btn btn-light mt-4" href="<?= app_url('doctors') ?>">Cancel</a></div></div></form>
